import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireAuth } from '@/lib/auth';

export const dynamic = 'force-dynamic';
const baixoGuandu = { name:'EJJ Baixo Guandu — Outubro 2026', location:'Av. Pres. Tancredo de Almeida Neves, 215 - Vila Kennedy, Baixo Guandu - ES', start:'2026-10-30', end:'2026-11-01', stops:'Ida — 30/10: 14:00 Shopping Moxuara (Cariacica); 14:30 UFES Goiabeiras (Vitória); 15:10 Supermercado BH Laranjeiras (Serra); 15:40 Rodoviária da Serra.\n\nNo destino: translado entre Igreja Adventista do Sétimo Dia (Av. Dez de Abril, Centro) e Vila Kennedy, com 2 viagens/translados entre sexta, sábado e domingo.\n\nRetorno — 01/11 às 20:30.' };
async function seed() { const sql=db(); const found=await sql`SELECT id FROM trips LIMIT 1`; if(!found.length) await sql`INSERT INTO trips (name,location,start_date,end_date,stops) VALUES (${baixoGuandu.name},${baixoGuandu.location},${baixoGuandu.start},${baixoGuandu.end},${baixoGuandu.stops})`; }
export async function GET(){try{await requireAuth();await seed();const rows=await db()`SELECT id,name,location,TO_CHAR(start_date,'YYYY-MM-DD') AS "startDate",TO_CHAR(end_date,'YYYY-MM-DD') AS "endDate",stops,created_at AS "createdAt" FROM trips ORDER BY start_date DESC`;return NextResponse.json(rows)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Não foi possível carregar viagens.'},{status:500})}}
export async function POST(request:NextRequest){try{await requireAuth();const b=await request.json(),name=String(b.name||'').trim(),location=String(b.location||'').trim(),start=String(b.startDate||''),end=String(b.endDate||''),stops=String(b.stops||'').trim();if(!name||!location||!start||!end||end<start)throw new Error('Preencha nome, local, início e fim corretamente.');const rows=await db()`INSERT INTO trips (name,location,start_date,end_date,stops) VALUES (${name},${location},${start},${end},${stops}) RETURNING id`;return NextResponse.json({id:rows[0].id},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Não foi possível salvar.'},{status:400})}}
