'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { Availability, BusType, Company, Quote, QuoteStatus, ReserveBus, Trip } from '@/lib/types';

type View = 'dashboard' | 'quotes' | 'companies' | 'trips';
const availability: Availability[] = ['Disponível', 'Sem disponibilidade nesta data', 'A confirmar'];
const reserves: ReserveBus[] = ['Possui ônibus reserva', 'Não possui ônibus reserva', 'Não informado'];
const statuses: QuoteStatus[] = ['Solicitada', 'Recebida', 'Em negociação', 'Selecionada', 'Recusada', 'Indisponível'];
const blankCompany = { contactName: '', companyName: '', whatsapp: '', busSize: '', busType: 'Executivo' as BusType };
const blankTrip = { name: '', tripDate: '' };
const blankQuote = { companyId: '', availability: 'A confirmar' as Availability, reserveBus: 'Não informado' as ReserveBus, totalValue: '', depositPercent: '', paymentMethod: '', status: 'Solicitada' as QuoteStatus, validUntil: '', proposalLink: '', notes: '' };

const money = (value: number | null) => value === null ? 'A combinar' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const label = (status: string) => <span className={'tag '+(status === 'Disponível' || status === 'Selecionada' ? 'green' : status.includes('indispon') || status === 'Recusada' ? 'red' : status === 'A confirmar' || status === 'Em negociação' ? 'amber' : 'blue')}>{status}</span>;
const storageKey = { companies: 'ejj.fretamentos.companies', quotes: 'ejj.fretamentos.quotes', trips: 'ejj.fretamentos.trips', selectedTrip: 'ejj.fretamentos.selectedTrip' };
const readLocal = <T,>(key:string):T[] => { try { return JSON.parse(window.localStorage.getItem(key) || '[]'); } catch { return []; } };
const writeLocal = <T,>(key:string, value:T[]) => window.localStorage.setItem(key, JSON.stringify(value));
const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"','""')}"`;
function downloadCsv(name:string, headers:string[], rows:unknown[][]) { const content=[headers.map(csvCell).join(';'),...rows.map(row=>row.map(csvCell).join(';'))].join('\n'); const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/csv;charset=utf-8'})); const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url); }
function downloadJson(name:string, data:unknown) { const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url); }

export default function Dashboard() {
  const [view, setView] = useState<View>('dashboard'); const [companies, setCompanies] = useState<Company[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]); const [trips,setTrips]=useState<Trip[]>([]);const [selectedTripId,setSelectedTripId]=useState('');const [dash, setDash] = useState({companies:0, available:0, received:0, lowestValue:null as number|null}); const [query, setQuery] = useState('');
  const [modal, setModal] = useState<'company'|'quote'|'trip'|null>(null); const [editId, setEditId] = useState<string|null>(null); const [companyForm, setCompanyForm] = useState(blankCompany);const [tripForm,setTripForm]=useState(blankTrip); const [quoteForm, setQuoteForm] = useState(blankQuote); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const load = () => { setLoading(true); const c=readLocal<Company>(storageKey.companies),q=readLocal<Quote>(storageKey.quotes),t=readLocal<Trip>(storageKey.trips);const current=window.localStorage.getItem(storageKey.selectedTrip)||t[0]?.id||'';const filtered=q.filter(x=>x.tripId===current);setCompanies(c);setQuotes(q);setTrips(t);setSelectedTripId(current);const values=filtered.filter(x=>x.availability==='Disponível'&&x.totalValue!==null).map(x=>x.totalValue as number);setDash({companies:c.length,available:filtered.filter(x=>x.availability==='Disponível').length,received:filtered.filter(x=>['Recebida','Em negociação','Selecionada'].includes(x.status)).length,lowestValue:values.length?Math.min(...values):null});setLoading(false); };
  useEffect(() => { fetch('/api/auth/me').then(r=>r.json()).then(x=>{setAuthenticated(x.authenticated);if(x.authenticated)load();}).catch(()=>setAuthenticated(false)); }, []);
  const tell = (message:string) => { setNotice(message); setTimeout(()=>setNotice(''),3500); };
  const openCompany = (item?: Company) => { setEditId(item?.id || null); setCompanyForm(item ? { contactName:item.contactName,companyName:item.companyName,whatsapp:item.whatsapp||'',busSize:String(item.busSize),busType:item.busType } : blankCompany); setModal('company'); };
  const openTrip = (item?:Trip) => {setEditId(item?.id||null);setTripForm(item?{name:item.name,tripDate:item.tripDate}:blankTrip);setModal('trip');};
  const openQuote = (item?: Quote) => { setEditId(item?.id || null); setQuoteForm(item ? { companyId:item.companyId, availability:item.availability,reserveBus:item.reserveBus,totalValue:item.totalValue === null?'':String(item.totalValue),depositPercent:item.depositPercent === null?'':String(item.depositPercent),paymentMethod:item.paymentMethod || '',status:item.status,validUntil:item.validUntil || '',proposalLink:item.proposalLink || '',notes:item.notes || '' } : blankQuote); setModal('quote'); };
  const saveCompany = (event:FormEvent) => { event.preventDefault(); const busSize=Number(companyForm.busSize);if(!companyForm.contactName.trim()||!companyForm.companyName.trim()||busSize<1){setError('Preencha nome, empresa e tamanho do ônibus.');return;}const item:Company={id:editId||crypto.randomUUID(),contactName:companyForm.contactName.trim(),companyName:companyForm.companyName.trim(),whatsapp:companyForm.whatsapp.trim(),busSize,busType:companyForm.busType,createdAt:new Date().toISOString()};writeLocal(storageKey.companies,editId?companies.map(x=>x.id===editId?item:x):[...companies,item]);setModal(null);tell(editId?'Empresa atualizada.':'Empresa cadastrada.');load(); };
  const saveTrip=(event:FormEvent)=>{event.preventDefault();if(!tripForm.name.trim()||!tripForm.tripDate){setError('Informe o nome e a data da viagem.');return;}const item:Trip={id:editId||crypto.randomUUID(),name:tripForm.name.trim(),tripDate:tripForm.tripDate,createdAt:new Date().toISOString()};const next=editId?trips.map(x=>x.id===editId?item:x):[...trips,item];writeLocal(storageKey.trips,next);if(!selectedTripId||editId===selectedTripId)window.localStorage.setItem(storageKey.selectedTrip,item.id);setModal(null);tell(editId?'Viagem atualizada.':'Viagem criada.');load();};
  const saveQuote = (event:FormEvent) => { event.preventDefault();const company=companies.find(x=>x.id===quoteForm.companyId);if(!selectedTripId){setError('Crie e selecione uma viagem antes de cadastrar orçamento.');return;}if(!company){setError('Selecione uma empresa.');return;}const total=quoteForm.totalValue===''?null:Number(quoteForm.totalValue);if(['Recebida','Em negociação','Selecionada'].includes(quoteForm.status)&&(!total||total<=0)){setError('Informe o valor total da proposta.');return;}let status=quoteForm.availability==='Sem disponibilidade nesta data'?'Indisponível':quoteForm.status;if(status==='Selecionada'&&quoteForm.availability!=='Disponível'){setError('Só é possível selecionar uma empresa disponível.');return;}const item:Quote={id:editId||crypto.randomUUID(),tripId:editId?quotes.find(x=>x.id===editId)?.tripId||selectedTripId:selectedTripId,companyId:company.id,contactName:company.contactName,companyName:company.companyName,busSize:company.busSize,busType:company.busType,availability:quoteForm.availability,reserveBus:quoteForm.reserveBus,totalValue:total,depositPercent:quoteForm.depositPercent===''?null:Number(quoteForm.depositPercent),paymentMethod:quoteForm.paymentMethod.trim()||null,status,validUntil:quoteForm.validUntil||null,proposalLink:quoteForm.proposalLink.trim()||null,notes:quoteForm.notes.trim()||null,createdAt:editId?quotes.find(x=>x.id===editId)?.createdAt||new Date().toISOString():new Date().toISOString()};let next=editId?quotes.map(x=>x.id===editId?item:x):[...quotes,item];if(status==='Selecionada')next=next.map(x=>x.id!==item.id&&x.tripId===item.tripId&&x.status==='Selecionada'?{...x,status:'Em negociação'}:x);writeLocal(storageKey.quotes,next);setModal(null);tell(editId?'Orçamento atualizado.':'Orçamento registrado.');load(); };
  const remove = (kind:'companies'|'quotes'|'trips', id:string) => { if(!confirm('Excluir este registro?')) return;if(kind==='companies'&&quotes.some(x=>x.companyId===id)){setError('Essa empresa possui orçamentos. Exclua os orçamentos antes.');return;}if(kind==='trips'&&quotes.some(x=>x.tripId===id)){setError('Essa viagem possui orçamentos. Exclua os orçamentos antes.');return;}if(kind==='companies')writeLocal(storageKey.companies,companies.filter(x=>x.id!==id));if(kind==='quotes')writeLocal(storageKey.quotes,quotes.filter(x=>x.id!==id));if(kind==='trips'){writeLocal(storageKey.trips,trips.filter(x=>x.id!==id));if(selectedTripId===id)window.localStorage.removeItem(storageKey.selectedTrip);}tell('Registro excluído.');load(); };
  const login=async(username:string,password:string)=>{const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const json=await res.json();if(!res.ok)throw new Error(json.error);setAuthenticated(true);setError('');load();}; const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuthenticated(false);setCompanies([]);setQuotes([]);};
  const activeTrip=trips.find(x=>x.id===selectedTripId);const chooseTrip=(id:string)=>{window.localStorage.setItem(storageKey.selectedTrip,id);setSelectedTripId(id);load();};
  const exportCurrent=()=>{const stamp=new Date().toISOString().slice(0,10);if(view==='dashboard'){downloadJson(`backup-fretamentos-${stamp}.json`,{exportadoEm:new Date().toISOString(),viagens:trips,empresas:companies,orcamentos:quotes});tell('Backup completo exportado.');return;}if(view==='companies'){downloadCsv(`empresas-${stamp}.csv`,['Nome','Empresa','WhatsApp','Tamanho do ônibus','Tipo'],shownCompanies.map(x=>[x.contactName,x.companyName,x.whatsapp,x.busSize,x.busType]));tell('Empresas exportadas.');return;}if(view==='trips'){downloadCsv(`viagens-${stamp}.csv`,['Nome','Data'],trips.map(x=>[x.name,x.tripDate]));tell('Viagens exportadas.');return;}downloadCsv(`orcamentos-${activeTrip?.name||stamp}.csv`,['Empresa','Contato','Tamanho','Tipo','Disponibilidade','Ônibus reserva','Valor total','Sinal (%)','Pagamento','Status','Validade','Observações','Link'],shownQuotes.map(x=>[x.companyName,x.contactName,x.busSize,x.busType,x.availability,x.reserveBus,x.totalValue,x.depositPercent,x.paymentMethod,x.status,x.validUntil,x.notes,x.proposalLink]));tell('Orçamentos exportados.');};
  const shownCompanies=useMemo(()=>companies.filter(x=>Object.values(x).join(' ').toLowerCase().includes(query.toLowerCase())),[companies,query]); const shownQuotes=useMemo(()=>quotes.filter(x=>x.tripId===selectedTripId).filter(x=>Object.values(x).join(' ').toLowerCase().includes(query.toLowerCase())),[quotes,query,selectedTripId]); const selected=shownQuotes.find(x=>x.status==='Selecionada');
  if(authenticated===null)return <main className="login-page"><div className="loader"/>Preparando acesso…</main>;
  if(!authenticated)return <Login onSubmit={login}/>;
  return <main>
    <header className="topbar"><div className="brand"><span className="mark">EJJ</span><div><strong>Fretamentos</strong><small>Baixo Guandu</small></div></div><nav>{([['dashboard','Visão geral'],['quotes','Orçamentos'],['companies','Empresas'],['trips','Viagens']] as [View,string][]).map(([id,name])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}>{name}</button>)}</nav><button className="signout" onClick={logout}>Sair</button><button className="new" onClick={()=>view==='companies'?openCompany():view==='trips'?openTrip():openQuote()}>{view==='companies'?'+ Nova empresa':view==='trips'?'+ Nova viagem':'+ Novo orçamento'}</button></header>
    <section className="shell">
      <div className="heading"><div><p className="eyebrow">LOGÍSTICA DA VIAGEM</p><h1>{view==='dashboard'?'Decida com clareza.':view==='quotes'?'Compare propostas.':view==='trips'?'Organize as viagens.':'Cadastre os parceiros.'}</h1><p>{view==='dashboard'?'Consolide as cotações e escolha a melhor empresa para a viagem.':view==='quotes'?'Disponibilidade e ônibus reserva são registrados para cada viagem.':view==='trips'?'Crie uma viagem, informe o nome e a data, depois acompanhe os seus orçamentos.':'O cadastro da empresa fica limpo: contato, empresa, WhatsApp e o ônibus oferecido.'}</p></div><div className="trip"><span>VIAGEM ATUAL</span>{trips.length?<select value={selectedTripId} onChange={e=>chooseTrip(e.target.value)}>{trips.map(x=><option value={x.id} key={x.id}>{x.name} · {x.tripDate.split('-').reverse().join('/')}</option>)}</select>:<button onClick={()=>openTrip()}>Criar viagem</button>}</div></div>
      {error && <div className="notice error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice && <div className="notice">{notice}</div>}
      {loading ? <div className="empty"><div className="loader"/>Carregando o painel…</div> : view==='dashboard' ? <DashboardView dash={dash} quotes={shownQuotes} selected={selected} setView={setView} openQuote={openQuote} exportAll={exportCurrent} activeTrip={activeTrip} openTrip={openTrip} /> : <section className="board"><div className="toolbar"><label>Buscar <input value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='trips'?'Nome da viagem':'Nome, empresa ou status'}/></label><span>{view==='quotes'?shownQuotes.length:view==='companies'?shownCompanies.length:trips.length} registro(s)</span><button className="export" onClick={exportCurrent}>Exportar CSV ↓</button></div>{view==='quotes'?<QuoteTable quotes={shownQuotes} open={openQuote} remove={id=>remove('quotes',id)} />:view==='companies'?<CompanyTable companies={shownCompanies} open={openCompany} remove={id=>remove('companies',id)} />:<TripTable trips={trips.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()))} current={selectedTripId} choose={chooseTrip} open={openTrip} remove={id=>remove('trips',id)} />}</section>}
    </section>
    {modal==='company' && <Modal title={editId?'Editar empresa':'Cadastrar empresa'} close={()=>setModal(null)}><form onSubmit={saveCompany} className="form"><Input label="Nome do contato" required value={companyForm.contactName} onChange={contactName=>setCompanyForm({...companyForm,contactName})}/><Input label="Empresa" required value={companyForm.companyName} onChange={companyName=>setCompanyForm({...companyForm,companyName})}/><Input label="WhatsApp" type="tel" value={companyForm.whatsapp} onChange={whatsapp=>setCompanyForm({...companyForm,whatsapp})}/><Input label="Tamanho do ônibus (lugares)" required type="number" value={companyForm.busSize} onChange={busSize=>setCompanyForm({...companyForm,busSize})}/><Select label="Tipo de ônibus" value={companyForm.busType} onChange={busType=>setCompanyForm({...companyForm,busType:busType as BusType})} options={['Executivo','Convencional']}/><FormFooter close={()=>setModal(null)} text="Salvar empresa"/></form></Modal>}
    {modal==='trip'&&<Modal title={editId?'Editar viagem':'Criar viagem'} close={()=>setModal(null)}><form onSubmit={saveTrip} className="form"><Input label="Nome da viagem" required wide value={tripForm.name} onChange={name=>setTripForm({...tripForm,name})}/><Input label="Data da viagem" required type="date" wide value={tripForm.tripDate} onChange={tripDate=>setTripForm({...tripForm,tripDate})}/><FormFooter close={()=>setModal(null)} text="Salvar viagem"/></form></Modal>}
    {modal==='quote' && <Modal title={editId?'Editar orçamento':'Novo orçamento'} close={()=>setModal(null)}><form onSubmit={saveQuote} className="form"><Select label="Empresa" required value={quoteForm.companyId} onChange={companyId=>setQuoteForm({...quoteForm,companyId})} options={companies.map(c=>({value:c.id,label:`${c.companyName} — ${c.contactName} (${c.busType}, ${c.busSize} lugares)`}))} placeholder="Selecione uma empresa"/><Select label="Disponibilidade nesta data" required value={quoteForm.availability} onChange={availability=>setQuoteForm({...quoteForm,availability:availability as Availability,status:availability==='Sem disponibilidade nesta data'?'Indisponível':quoteForm.status})} options={availability}/><Select label="Ônibus reserva" required value={quoteForm.reserveBus} onChange={reserveBus=>setQuoteForm({...quoteForm,reserveBus:reserveBus as ReserveBus})} options={reserves}/><Input label="Valor total" type="number" value={quoteForm.totalValue} onChange={totalValue=>setQuoteForm({...quoteForm,totalValue})}/><Input label="Sinal (%)" type="number" value={quoteForm.depositPercent} onChange={depositPercent=>setQuoteForm({...quoteForm,depositPercent})}/><Select label="Status do orçamento" required value={quoteForm.status} onChange={status=>setQuoteForm({...quoteForm,status:status as QuoteStatus})} options={statuses}/><Input label="Validade" type="date" value={quoteForm.validUntil} onChange={validUntil=>setQuoteForm({...quoteForm,validUntil})}/><Input label="Forma de pagamento" wide value={quoteForm.paymentMethod} onChange={paymentMethod=>setQuoteForm({...quoteForm,paymentMethod})}/><Input label="Link da proposta" type="url" wide value={quoteForm.proposalLink} onChange={proposalLink=>setQuoteForm({...quoteForm,proposalLink})}/><label className="field wide">Observações<textarea value={quoteForm.notes} onChange={e=>setQuoteForm({...quoteForm,notes:e.target.value})}/></label><FormFooter close={()=>setModal(null)} text="Salvar orçamento"/></form></Modal>}
  </main>;
}

function DashboardView({dash,quotes,selected,setView,openQuote,exportAll,activeTrip,openTrip}:{dash:{companies:number;available:number;received:number;lowestValue:number|null};quotes:Quote[];selected?:Quote;setView:(v:View)=>void;openQuote:(q:Quote)=>void;exportAll:()=>void;activeTrip?:Trip;openTrip:()=>void}) { if(!activeTrip)return <><div className="overview-actions"><span>Dados salvos somente neste navegador</span><button className="export" onClick={exportAll}>Exportar backup completo ↓</button></div><div className="empty"><h2>Crie a primeira viagem</h2><p className="empty-copy">Cadastre o nome e a data da viagem para começar a receber orçamentos.</p><button className="new" onClick={openTrip}>+ Criar viagem</button></div></>;return <><div className="overview-actions"><span>Dados da viagem: {activeTrip.name} · {activeTrip.tripDate.split('-').reverse().join('/')}</span><button className="export" onClick={exportAll}>Exportar backup completo ↓</button></div><section className="metrics"><Metric num={dash.companies} label="empresas cadastradas"/><Metric num={dash.available} label="disponíveis na data" tone="green"/><Metric num={dash.received} label="propostas em análise" tone="blue"/><Metric num={money(dash.lowestValue)} label="menor valor disponível" tone="gold"/></section><section className="decision"><div className="recent"><div className="sectiontitle"><div><p className="eyebrow">MOVIMENTO RECENTE</p><h2>Orçamentos</h2></div><button className="link" onClick={()=>setView('quotes')}>Ver todos →</button></div>{quotes.length?quotes.slice(0,5).map(q=><button key={q.id} className="quote-row" onClick={()=>openQuote(q)}><span><b>{q.companyName}</b><small>{q.busType} · {q.busSize} lugares · {q.reserveBus}</small></span><span><b>{money(q.totalValue)}</b>{label(q.status)}</span></button>):<Empty text="Comece cadastrando uma empresa e o primeiro orçamento desta viagem."/>}</div><aside className="choice"><p className="eyebrow">ESCOLHA ATUAL</p>{selected?<><h2>{selected.companyName}</h2><b className="bigvalue">{money(selected.totalValue)}</b><p>{selected.contactName} · {selected.busType} · {selected.busSize} lugares</p>{label('Selecionada')}</>:<><h2>Nenhuma escolhida</h2><p>Quando uma empresa estiver disponível, marque a proposta como selecionada.</p></>}</aside></section></> }
function Metric({num,label,tone='ink'}:{num:number|string;label:string;tone?:string}) {return <article className={'metric '+tone}><strong>{num}</strong><span>{label}</span></article>}
function QuoteTable({quotes,open,remove}:{quotes:Quote[];open:(q:Quote)=>void;remove:(id:string)=>void}) {return <table><thead><tr><th>Empresa / ônibus</th><th>Disponibilidade</th><th>Valor</th><th>Status</th><th/></tr></thead><tbody>{quotes.length?quotes.map(q=><tr key={q.id}><td><b>{q.companyName}</b><small>{q.contactName} · {q.busType} · {q.busSize} lugares</small></td><td>{label(q.availability)}<small>{q.reserveBus}</small></td><td><b>{money(q.totalValue)}</b></td><td>{label(q.status)}</td><td className="actions"><button onClick={()=>open(q)}>Editar</button><button className="danger" onClick={()=>remove(q.id)}>Excluir</button></td></tr>):<tr><td colSpan={5}><Empty text="Nenhum orçamento encontrado."/></td></tr>}</tbody></table>}
function CompanyTable({companies,open,remove}:{companies:Company[];open:(c:Company)=>void;remove:(id:string)=>void}) {return <table><thead><tr><th>Contato</th><th>Empresa</th><th>WhatsApp</th><th>Ônibus</th><th/></tr></thead><tbody>{companies.length?companies.map(c=><tr key={c.id}><td><b>{c.contactName}</b></td><td>{c.companyName}</td><td>{c.whatsapp||'—'}</td><td>{c.busType}<small>{c.busSize} lugares</small></td><td className="actions"><button onClick={()=>open(c)}>Editar</button><button className="danger" onClick={()=>remove(c.id)}>Excluir</button></td></tr>):<tr><td colSpan={5}><Empty text="Nenhuma empresa cadastrada."/></td></tr>}</tbody></table>}
function TripTable({trips,current,choose,open,remove}:{trips:Trip[];current:string;choose:(id:string)=>void;open:(t:Trip)=>void;remove:(id:string)=>void}) {return <table><thead><tr><th>Viagem</th><th>Data</th><th>Status</th><th/></tr></thead><tbody>{trips.length?trips.map(t=><tr key={t.id}><td><b>{t.name}</b></td><td>{t.tripDate.split('-').reverse().join('/')}</td><td>{t.id===current?<span className="tag green">Ativa</span>:<button className="link" onClick={()=>choose(t.id)}>Selecionar</button>}</td><td className="actions"><button onClick={()=>open(t)}>Editar</button><button className="danger" onClick={()=>remove(t.id)}>Excluir</button></td></tr>):<tr><td colSpan={4}><Empty text="Nenhuma viagem cadastrada."/></td></tr>}</tbody></table>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) {return <div className="veil" role="dialog" aria-modal="true"><section className="modal"><header><div><p className="eyebrow">FRETAMENTOS EJJ</p><h2>{title}</h2></div><button onClick={close} className="close">×</button></header>{children}</section></div>}
function Input({label,value,onChange,type='text',required=false,wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;wide?:boolean}) {return <label className={'field '+(wide?'wide':'')}>{label}{required&&' *'}<input type={type} required={required} value={value} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options,placeholder,required=false}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];placeholder?:string;required?:boolean}) {return <label className="field">{label}{required&&' *'}<select required={required} value={value} onChange={e=>onChange(e.target.value)}>{placeholder&&<option value="">{placeholder}</option>}{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function FormFooter({close,text}:{close:()=>void;text:string}) {return <div className="form-footer"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">{text}</button></div>}
function Empty({text}:{text:string}) {return <p className="empty-copy">{text}</p>}
function Login({onSubmit}:{onSubmit:(username:string,password:string)=>Promise<void>}) { const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [sending,setSending]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setSending(true);setError('');try{await onSubmit(username,password)}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setSending(false)}};return <main className="login-page"><section className="login-card"><div className="login-mark">EJJ</div><p className="eyebrow">CENTRAL DE FRETAMENTOS</p><h1>Entre para acompanhar a viagem.</h1><p>Empresas, cotações e decisão final em um único lugar.</p><form onSubmit={submit}><label>Usuário<input autoFocus value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error">{error}</div>}<button className="login-button" disabled={sending}>{sending?'Entrando…':'Entrar'}</button></form></section></main>}
