'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { Availability, BusType, Company, Quote, QuoteStatus, ReserveBus } from '@/lib/types';

type View = 'dashboard' | 'quotes' | 'companies';
const availability: Availability[] = ['Disponível', 'Sem disponibilidade nesta data', 'A confirmar'];
const reserves: ReserveBus[] = ['Possui ônibus reserva', 'Não possui ônibus reserva', 'Não informado'];
const statuses: QuoteStatus[] = ['Solicitada', 'Recebida', 'Em negociação', 'Selecionada', 'Recusada', 'Indisponível'];
const blankCompany = { contactName: '', companyName: '', busSize: '', busType: 'Executivo' as BusType };
const blankQuote = { companyId: '', availability: 'A confirmar' as Availability, reserveBus: 'Não informado' as ReserveBus, totalValue: '', depositPercent: '', paymentMethod: '', status: 'Solicitada' as QuoteStatus, validUntil: '', proposalLink: '', notes: '' };

const money = (value: number | null) => value === null ? 'A combinar' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const label = (status: string) => <span className={'tag '+(status === 'Disponível' || status === 'Selecionada' ? 'green' : status.includes('indispon') || status === 'Recusada' ? 'red' : status === 'A confirmar' || status === 'Em negociação' ? 'amber' : 'blue')}>{status}</span>;

export default function Dashboard() {
  const [view, setView] = useState<View>('dashboard'); const [companies, setCompanies] = useState<Company[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]); const [dash, setDash] = useState({companies:0, available:0, received:0, lowestValue:null as number|null}); const [query, setQuery] = useState('');
  const [modal, setModal] = useState<'company'|'quote'|null>(null); const [editId, setEditId] = useState<string|null>(null); const [companyForm, setCompanyForm] = useState(blankCompany); const [quoteForm, setQuoteForm] = useState(blankQuote); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const load = async () => { setLoading(true); try { const [c,q,d] = await Promise.all([fetch('/api/companies'),fetch('/api/quotes'),fetch('/api/dashboard')]); if (!c.ok || !q.ok || !d.ok) throw new Error('Não foi possível carregar os dados. Verifique a conexão com o banco.'); setCompanies(await c.json()); setQuotes(await q.json()); setDash(await d.json()); } catch(e) { setError(e instanceof Error ? e.message : 'Erro ao carregar.'); } finally { setLoading(false); } };
  useEffect(() => { fetch('/api/auth/me').then(r=>r.json()).then(x=>{setAuthenticated(x.authenticated);if(x.authenticated)load();}).catch(()=>setAuthenticated(false)); }, []);
  const tell = (message:string) => { setNotice(message); setTimeout(()=>setNotice(''),3500); };
  const openCompany = (item?: Company) => { setEditId(item?.id || null); setCompanyForm(item ? { contactName:item.contactName,companyName:item.companyName,busSize:String(item.busSize),busType:item.busType } : blankCompany); setModal('company'); };
  const openQuote = (item?: Quote) => { setEditId(item?.id || null); setQuoteForm(item ? { companyId:item.companyId, availability:item.availability,reserveBus:item.reserveBus,totalValue:item.totalValue === null?'':String(item.totalValue),depositPercent:item.depositPercent === null?'':String(item.depositPercent),paymentMethod:item.paymentMethod || '',status:item.status,validUntil:item.validUntil || '',proposalLink:item.proposalLink || '',notes:item.notes || '' } : blankQuote); setModal('quote'); };
  const saveCompany = async (event:FormEvent) => { event.preventDefault(); const url=editId?`/api/companies/${editId}`:'/api/companies'; const res=await fetch(url,{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(companyForm)}); const json=await res.json(); if(!res.ok){setError(json.error);return;} setModal(null); tell(editId?'Empresa atualizada.':'Empresa cadastrada.'); load(); };
  const saveQuote = async (event:FormEvent) => { event.preventDefault(); const url=editId?`/api/quotes/${editId}`:'/api/quotes'; const res=await fetch(url,{method:editId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(quoteForm)}); const json=await res.json(); if(!res.ok){setError(json.error);return;} setModal(null); tell(editId?'Orçamento atualizado.':'Orçamento registrado.'); load(); };
  const remove = async (kind:'companies'|'quotes', id:string) => { if(!confirm('Excluir este registro?')) return; const res=await fetch(`/api/${kind}/${id}`,{method:'DELETE'}); const json=await res.json(); if(!res.ok){setError(json.error);return;} tell('Registro excluído.'); load(); };
  const login=async(username:string,password:string)=>{const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const json=await res.json();if(!res.ok)throw new Error(json.error);setAuthenticated(true);setError('');load();}; const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuthenticated(false);setCompanies([]);setQuotes([]);};
  const shownCompanies=useMemo(()=>companies.filter(x=>Object.values(x).join(' ').toLowerCase().includes(query.toLowerCase())),[companies,query]); const shownQuotes=useMemo(()=>quotes.filter(x=>Object.values(x).join(' ').toLowerCase().includes(query.toLowerCase())),[quotes,query]); const selected=quotes.find(x=>x.status==='Selecionada');
  if(authenticated===null)return <main className="login-page"><div className="loader"/>Preparando acesso…</main>;
  if(!authenticated)return <Login onSubmit={login}/>;
  return <main>
    <header className="topbar"><div className="brand"><span className="mark">EJJ</span><div><strong>Fretamentos</strong><small>Baixo Guandu</small></div></div><nav>{([['dashboard','Visão geral'],['quotes','Orçamentos'],['companies','Empresas']] as [View,string][]).map(([id,name])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}>{name}</button>)}</nav><button className="signout" onClick={logout}>Sair</button><button className="new" onClick={()=>view==='companies'?openCompany():openQuote()}>{view==='companies'?'+ Nova empresa':'+ Novo orçamento'}</button></header>
    <section className="shell">
      <div className="heading"><div><p className="eyebrow">LOGÍSTICA DA VIAGEM</p><h1>{view==='dashboard'?'Decida com clareza.':view==='quotes'?'Compare propostas.':'Cadastre os parceiros.'}</h1><p>{view==='dashboard'?'Consolide as cotações e escolha a melhor empresa para a viagem.':view==='quotes'?'Disponibilidade e ônibus reserva são registrados para cada orçamento.':'O cadastro da empresa fica limpo: contato, empresa e o ônibus oferecido.'}</p></div><div className="trip"><span>30 OUT — 01 NOV</span><b>46 passageiros</b></div></div>
      {error && <div className="notice error">{error}<button onClick={()=>setError('')}>×</button></div>}{notice && <div className="notice">{notice}</div>}
      {loading ? <div className="empty"><div className="loader"/>Carregando o painel…</div> : view==='dashboard' ? <DashboardView dash={dash} quotes={quotes} selected={selected} setView={setView} openQuote={openQuote} /> : <section className="board"><div className="toolbar"><label>Buscar <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, empresa ou status"/></label><span>{view==='quotes'?shownQuotes.length:shownCompanies.length} registro(s)</span></div>{view==='quotes'?<QuoteTable quotes={shownQuotes} open={openQuote} remove={id=>remove('quotes',id)} />:<CompanyTable companies={shownCompanies} open={openCompany} remove={id=>remove('companies',id)} />}</section>}
    </section>
    {modal==='company' && <Modal title={editId?'Editar empresa':'Cadastrar empresa'} close={()=>setModal(null)}><form onSubmit={saveCompany} className="form"><Input label="Nome do contato" required value={companyForm.contactName} onChange={contactName=>setCompanyForm({...companyForm,contactName})}/><Input label="Empresa" required value={companyForm.companyName} onChange={companyName=>setCompanyForm({...companyForm,companyName})}/><Input label="Tamanho do ônibus (lugares)" required type="number" value={companyForm.busSize} onChange={busSize=>setCompanyForm({...companyForm,busSize})}/><Select label="Tipo de ônibus" value={companyForm.busType} onChange={busType=>setCompanyForm({...companyForm,busType:busType as BusType})} options={['Executivo','Convencional']}/><FormFooter close={()=>setModal(null)} text="Salvar empresa"/></form></Modal>}
    {modal==='quote' && <Modal title={editId?'Editar orçamento':'Novo orçamento'} close={()=>setModal(null)}><form onSubmit={saveQuote} className="form"><Select label="Empresa" required value={quoteForm.companyId} onChange={companyId=>setQuoteForm({...quoteForm,companyId})} options={companies.map(c=>({value:c.id,label:`${c.companyName} — ${c.contactName} (${c.busType}, ${c.busSize} lugares)`}))} placeholder="Selecione uma empresa"/><Select label="Disponibilidade nesta data" required value={quoteForm.availability} onChange={availability=>setQuoteForm({...quoteForm,availability:availability as Availability,status:availability==='Sem disponibilidade nesta data'?'Indisponível':quoteForm.status})} options={availability}/><Select label="Ônibus reserva" required value={quoteForm.reserveBus} onChange={reserveBus=>setQuoteForm({...quoteForm,reserveBus:reserveBus as ReserveBus})} options={reserves}/><Input label="Valor total" type="number" value={quoteForm.totalValue} onChange={totalValue=>setQuoteForm({...quoteForm,totalValue})}/><Input label="Sinal (%)" type="number" value={quoteForm.depositPercent} onChange={depositPercent=>setQuoteForm({...quoteForm,depositPercent})}/><Select label="Status do orçamento" required value={quoteForm.status} onChange={status=>setQuoteForm({...quoteForm,status:status as QuoteStatus})} options={statuses}/><Input label="Validade" type="date" value={quoteForm.validUntil} onChange={validUntil=>setQuoteForm({...quoteForm,validUntil})}/><Input label="Forma de pagamento" wide value={quoteForm.paymentMethod} onChange={paymentMethod=>setQuoteForm({...quoteForm,paymentMethod})}/><Input label="Link da proposta" type="url" wide value={quoteForm.proposalLink} onChange={proposalLink=>setQuoteForm({...quoteForm,proposalLink})}/><label className="field wide">Observações<textarea value={quoteForm.notes} onChange={e=>setQuoteForm({...quoteForm,notes:e.target.value})}/></label><FormFooter close={()=>setModal(null)} text="Salvar orçamento"/></form></Modal>}
  </main>;
}

function DashboardView({dash,quotes,selected,setView,openQuote}:{dash:{companies:number;available:number;received:number;lowestValue:number|null};quotes:Quote[];selected?:Quote;setView:(v:View)=>void;openQuote:(q:Quote)=>void}) { return <><section className="metrics"><Metric num={dash.companies} label="empresas cadastradas"/><Metric num={dash.available} label="disponíveis na data" tone="green"/><Metric num={dash.received} label="propostas em análise" tone="blue"/><Metric num={money(dash.lowestValue)} label="menor valor disponível" tone="gold"/></section><section className="decision"><div className="recent"><div className="sectiontitle"><div><p className="eyebrow">MOVIMENTO RECENTE</p><h2>Orçamentos</h2></div><button className="link" onClick={()=>setView('quotes')}>Ver todos →</button></div>{quotes.length?quotes.slice(0,5).map(q=><button key={q.id} className="quote-row" onClick={()=>openQuote(q)}><span><b>{q.companyName}</b><small>{q.busType} · {q.busSize} lugares · {q.reserveBus}</small></span><span><b>{money(q.totalValue)}</b>{label(q.status)}</span></button>):<Empty text="Comece cadastrando uma empresa e o primeiro orçamento."/>}</div><aside className="choice"><p className="eyebrow">ESCOLHA ATUAL</p>{selected?<><h2>{selected.companyName}</h2><b className="bigvalue">{money(selected.totalValue)}</b><p>{selected.contactName} · {selected.busType} · {selected.busSize} lugares</p>{label('Selecionada')}</>:<><h2>Nenhuma escolhida</h2><p>Quando uma empresa estiver disponível, marque a proposta como selecionada.</p></>}</aside></section></> }
function Metric({num,label,tone='ink'}:{num:number|string;label:string;tone?:string}) {return <article className={'metric '+tone}><strong>{num}</strong><span>{label}</span></article>}
function QuoteTable({quotes,open,remove}:{quotes:Quote[];open:(q:Quote)=>void;remove:(id:string)=>void}) {return <table><thead><tr><th>Empresa / ônibus</th><th>Disponibilidade</th><th>Valor</th><th>Status</th><th/></tr></thead><tbody>{quotes.length?quotes.map(q=><tr key={q.id}><td><b>{q.companyName}</b><small>{q.contactName} · {q.busType} · {q.busSize} lugares</small></td><td>{label(q.availability)}<small>{q.reserveBus}</small></td><td><b>{money(q.totalValue)}</b></td><td>{label(q.status)}</td><td className="actions"><button onClick={()=>open(q)}>Editar</button><button className="danger" onClick={()=>remove(q.id)}>Excluir</button></td></tr>):<tr><td colSpan={5}><Empty text="Nenhum orçamento encontrado."/></td></tr>}</tbody></table>}
function CompanyTable({companies,open,remove}:{companies:Company[];open:(c:Company)=>void;remove:(id:string)=>void}) {return <table><thead><tr><th>Contato</th><th>Empresa</th><th>Ônibus</th><th/></tr></thead><tbody>{companies.length?companies.map(c=><tr key={c.id}><td><b>{c.contactName}</b></td><td>{c.companyName}</td><td>{c.busType}<small>{c.busSize} lugares</small></td><td className="actions"><button onClick={()=>open(c)}>Editar</button><button className="danger" onClick={()=>remove(c.id)}>Excluir</button></td></tr>):<tr><td colSpan={4}><Empty text="Nenhuma empresa cadastrada."/></td></tr>}</tbody></table>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) {return <div className="veil" role="dialog" aria-modal="true"><section className="modal"><header><div><p className="eyebrow">FRETAMENTOS EJJ</p><h2>{title}</h2></div><button onClick={close} className="close">×</button></header>{children}</section></div>}
function Input({label,value,onChange,type='text',required=false,wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;wide?:boolean}) {return <label className={'field '+(wide?'wide':'')}>{label}{required&&' *'}<input type={type} required={required} value={value} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options,placeholder,required=false}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];placeholder?:string;required?:boolean}) {return <label className="field">{label}{required&&' *'}<select required={required} value={value} onChange={e=>onChange(e.target.value)}>{placeholder&&<option value="">{placeholder}</option>}{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
function FormFooter({close,text}:{close:()=>void;text:string}) {return <div className="form-footer"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary">{text}</button></div>}
function Empty({text}:{text:string}) {return <p className="empty-copy">{text}</p>}
function Login({onSubmit}:{onSubmit:(username:string,password:string)=>Promise<void>}) { const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [sending,setSending]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setSending(true);setError('');try{await onSubmit(username,password)}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setSending(false)}};return <main className="login-page"><section className="login-card"><div className="login-mark">EJJ</div><p className="eyebrow">CENTRAL DE FRETAMENTOS</p><h1>Entre para acompanhar a viagem.</h1><p>Empresas, cotações e decisão final em um único lugar.</p><form onSubmit={submit}><label>Usuário<input autoFocus value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="login-error">{error}</div>}<button className="login-button" disabled={sending}>{sending?'Entrando…':'Entrar'}</button></form></section></main>}
